#!/bin/bash

ulimit -n 4096

NPM_BIN_PATH=$(cd `dirname $0`/node_modules/.bin; echo $PWD)

if [ "$1" = "--debug" ]; then
    npm --save-optional install;
    PATH=$NPM_BIN_PATH:$PATH grunt --debug;
elif [ "$1" = "runOnce" ]; then
    npm install;
    PATH=$NPM_BIN_PATH:$PATH grunt runOnce --debug;
 else
    npm --silent --save-optional install;
    PATH=$NPM_BIN_PATH:$PATH grunt;
fi
